server:
  port: 8080
  session:
    timeout: 600
spring:
  session:
    store-type: none
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///security?useUnicode=true&useSSL=false&characterEncodging=UTF-8
    username: root
    password: 1234
    tomcat:
      max-active: 100
      max-idle: 10
      test-on-borrow: true
      test-on-connect: true
      test-on-return: true 
      min-evictable-idle-time-millis: 1800000
      validation-query: select 1
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
        format_sql: true
isecurity:
  browser:
    login-type: redirect
    sing-up-url: /manage.html  
  social:
    qq:
      provider-id: qq
      app-id: 101386962
      app-secret: 2a0f820407df400b84a854d054be8b6a 
