spring:
  session:
    timeout: 1000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///security?useUnicode=true&useSSL=false&characterEncodging=UTF-8
    username: root
    password: 1234
    
isecurity:
  social:
    qq:
      provider-id: qq
      app-id: 101386962
      app-secret: 2a0f820407df400b84a854d054be8b6a
    weixin:
      app-id: 101386962
      app-secret: 2a0f820407df400b84a854d054be8b6a
    
